version: "3"

services:

  redis:
    build: redis
    image: redis-gslb:latest
    logging:
            driver: "json-file"
            options:
                    max-file: "1"
                    max-size: "200m"
    container_name: redis
    hostname: "redis"
    volumes:
     - ./redis/data:/data
    ports:
     - "6379:6379"
    stop_grace_period: 3s
    restart: unless-stopped
    command:
     - "redis-server"
     - "--requirepass b66056f86915a24e27877ef6ab4d8c4b15652c9139b09abfa5844ec1231379c5"
     - "--save ''"
     - "--appendonly no"
     - "--tcp-backlog 65536"
     - "--slave-serve-stale-data yes"
     - "--slave-read-only yes"
     - "--maxclients 10000"
    networks:
      gslb_net:
        ipv4_address: 172.21.0.2
    healthcheck:
      test: ["CMD","health-check.sh"]
      timeout: 10s
      retries: 3

  authoritative:
    build: authoritative
    image: powerdns-prometheus:latest
    logging:
            driver: "json-file"
            options:
                    max-file: "1"
                    max-size: "200m"
    container_name: authoritative
    hostname: "authoritative"
    working_dir: /etc/pdns
    volumes:
     - ./authoritative/pdns.conf:/etc/pdns/pdns.conf:ro
     - ./powergslb/:/opt/powergslb/:ro
    ports:
     - "5300:5300"
     - "5300:5300/udp"
     - "9120:8081"
    stop_grace_period: 3s
    restart: unless-stopped
    networks:
      gslb_net:
        ipv4_address: 172.21.0.3
    healthcheck:
      test: ["CMD","pdns_control", "ping"]
      timeout: 10s
      retries: 3

  powergslb:
    build: powergslb
    image: powergslb-gslb:latest
    logging:
            driver: "json-file"
            options:
                    max-file: "1"
                    max-size: "200m"
    container_name: powergslb
    hostname: "powergslb"
    working_dir: /opt/powergslb
    volumes:
     - ./powergslb/:/opt/powergslb/:ro
    ports:
     - "8080:8080"
    stop_grace_period: 3s
    restart: unless-stopped
    command: /opt/powergslb/powergslb -c /opt/powergslb/powergslb.conf
    networks:
      gslb_net:
        ipv4_address: 172.21.0.4
    healthcheck:
      test: ["CMD","health-check.sh"]
      timeout: 10s
      retries: 3

  dnsdist:
    build: dnsdist
    image: dnsdist-gslb:latest
    logging:
            driver: "json-file"
            options:
                    max-file: "1"
                    max-size: "200m"
    working_dir: /etc/dnsdist
    container_name: dnsdist
    hostname: "dnsdist"
    volumes:
      - ./dnsdist/dnsdist.conf:/etc/dnsdist/dnsdist.conf:ro
    ports:
     - "53:53/tcp"
     - "53:53/udp"
     - "8083:8083/tcp"
    stop_grace_period: 3s
    restart: unless-stopped
    tty: true
    stdin_open: true
    command: ["--disable-syslog", "--uid", "dnsdist", "--gid", "dnsdist", "--verbose"]
    networks:
      gslb_net:
        ipv4_address: 172.21.0.5
    healthcheck:
      test: ["CMD","health-check.sh"]
      timeout: 10s
      retries: 3

networks:
  gslb_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      com.docker.network.driver.mtu: "1500"
    ipam:
      driver: default
      config:
      - subt: ["CMD","health-check.sh"]
      timeout: 10s
      retries: 3

networks:
  gslb_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      com.docker.network.driver.mtu: "1500"
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
